apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fhc5738zd-nodejs
  janus-idp.io/tekton: fhc5738zd-nodejs
  backstage.io/kubernetes-id: fhc5738zd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fhc5738zd-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
